const SET_VIEW_MODE = 'SET_VIEW_MODE';
const SET_USER = 'SET_USER';
const SET_EVENTS = 'SET_EVENTS';
const SET_LIST_VIEW = 'SET_LIST_VIEW';
const SET_TIMEZONE = 'SET_TIMEZONE';
const SET_TASK = 'SET_TASK';
const SET_COLOR = 'SET_COLOR';
const SET_SELECTED_ITEMS = 'SET_SELECTED_ITEMS';
const SET_SELECTED_ITEMS_VISIBILITY = 'SET_SELECTED_ITEMS_VISIBILITY';
const SET_TABLE_EDIT_MODE = 'SET_TABLE_EDIT_MODE';
const SET_FONT_SIZE = 'SET_FONT_SIZE';

export {
  SET_VIEW_MODE,
  SET_USER,
  SET_EVENTS,
  SET_LIST_VIEW,
  SET_TIMEZONE,
  SET_TASK,
  SET_COLOR,
  SET_SELECTED_ITEMS,
  SET_SELECTED_ITEMS_VISIBILITY,
  SET_TABLE_EDIT_MODE,
  SET_FONT_SIZE,
};
