const SET_VIEW_MODE = 'SET_VIEW_MODE';
const SET_USER = 'SET_USER';
const SET_EVENTS = 'SET_EVENTS';
const SET_LIST_VIEW = 'SET_LIST_VIEW';
const SET_TIMEZONE = 'SET_LIST_VIEW';

export { SET_VIEW_MODE, SET_USER, SET_EVENTS, SET_LIST_VIEW, SET_TIMEZONE };
