const MILLISECONDS = 1000;
const INACTIVE_EVENT_TYPE = 'secondary';
const INACTIVE_EVENT_COLOR = '#00000073';
const LARGE_MOBILE_WIDTH = 500;

export { MILLISECONDS, INACTIVE_EVENT_TYPE, INACTIVE_EVENT_COLOR, LARGE_MOBILE_WIDTH };
