const INACTIVE_EVENT_TYPE = 'secondary';
const INACTIVE_EVENT_COLOR = '#00000073';
const LARGE_MOBILE_WIDTH = 600;
const DESKTOP_WIDTH = 1020;
const CALENDAR_FONT_SIZE = 16;
const BADGE_HEIGHT = 25;

export {
  INACTIVE_EVENT_TYPE,
  INACTIVE_EVENT_COLOR,
  LARGE_MOBILE_WIDTH,
  DESKTOP_WIDTH,
  CALENDAR_FONT_SIZE,
  BADGE_HEIGHT,
};
