const DATA = [
  {
    week: 0,
    name: 'Computer Science Basics',
    description:
      'Курс состоит из нескольких крупных модулей, каждый из которых содержит короткие видео и тесты. Задача тестов - проверить, насколько хорошо стала понятна тема. Тесты можно проходить неограниченное количество раз, более того, во многих из них есть пояснения к неправильным ответам. Этот курс максимально гибкий: нет дедлайнов, нет возможности "завалить" тест, можно проходить обучение в удобное время в удобном месте.',
    descriptionUrl: 'https://learn.epam.com/detailsPage?id=4b131384-7829-4204-a27b-21c538b41f88',
    type: ['JS task'],
    timeZone: '',
    estimatedTime: '16h',
    dateTime: '1598972400',
    place: 'online',
    comment:
      'Курс проходится за полчаса кликами по кнопке Next и перебором вариантов ответа в тестах. ',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1599004800',
    links: {},
  },
  {
    week: 0,
    name: 'HTML online course',
    description: 'Базовый курс по HTML',
    descriptionUrl: 'https://ru.code-basics.com/languages/html',
    type: ['HTML task', 'self-study'],
    timeZone: '',
    estimatedTime: '8h',
    dateTime: '1598972400',
    place: 'online',
    comment:
      'На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)/ Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1599004800',
    links: {},
  },
  {
    week: 0,
    name: 'CSS online course',
    description: 'Базовый курс по CSS',
    descriptionUrl: 'https://ru.code-basics.com/languages/css',
    type: ['CSS task', 'self-study'],
    timeZone: '',
    estimatedTime: '8h',
    dateTime: '1598972400',
    place: 'online',
    comment:
      'На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)/ Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски',
    organizer: ['DVgluQnLGTg9ggTi6A4N', 'zom0bgoUBztJLlMhDEvh'],
    deadline: '1599004800',
    links: {},
  },
  {
    week: 0,
    name: 'JS online course',
    description:
      'Базовый курс JavaScript. Если проходить осмысленно, даст неплохое представление о языке и его возможностях.',
    descriptionUrl: 'https://ru.code-basics.com/languages/javascript',
    type: ['JS task', 'self-study'],
    timeZone: '',
    estimatedTime: '8h',
    dateTime: '1598972400',
    place: 'online',
    comment:
      'На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)/ Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '1599004800',
    links: {},
  },
  {
    week: 1,
    name: 'Git & GitHub. Регистрация на GitHub',
    description: 'Знакомство с Git & GitHub , регистрация на сервесе, и установка Git',
    descriptionUrl: 'https://htmlacademy.ru/blog/boost/tools/register-on-github-work-with-console',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599469200',
    place: 'online',
    comment: 'Изучение и установка займет примерно 1 час. ',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'Git & GitHub. Изучение команд Git',
    description:
      'Создание репозитория на гитхабе, создание ветки, добавление файлов с использование команд Git',
    descriptionUrl: 'https://htmlacademy.ru/blog/boost/tools/useful-commands-for-working-with-git',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599469200',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['zom0bgoUBztJLlMhDEvh', '2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'Git & GitHub. Требования к комитам',
    description: 'Изучение требований коммитам согласно гайдлайну и применение их на практике',
    descriptionUrl: 'https://docs.rs.school/#/git-convention',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599555600',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'Git & GitHub. GitHub Pages',
    description: 'Изучение и использование сервиса GitHub Pages и Netlify для деплоя  проектов',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/create-github-pages.md',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599555600',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'IDE. Установка VS Code',
    description: 'YouTube видео по установленовке Visual Studio Code и рекомендованных плагинов. ',
    descriptionUrl: 'https://www.youtube.com/watch?v=5M6RL3MAGJU&feature=youtu.be',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '1h',
    dateTime: '1599642000',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {
      'VS Code Downloader': 'https://code.visualstudio.com/',
    },
  },
  {
    week: 1,
    name: 'IDE. Взаимодействие редактора и браузера',
    description: 'Изучение плагин LiveServer для открытия HTML файлов в браузере через VS Code',
    descriptionUrl: 'https://htmlacademy.ru/blog/education/all/how-to-run-html',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599642000',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'Markdown.',
    description: 'Изучение синтаксиса Markdown его применение на практике.',
    descriptionUrl: 'https://guides.hexlet.io/markdown/',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599728400',
    place: 'online',
    comment: 'Изучение займет примерно 1 час. ',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {
      'Mastering Markdown': 'https://guides.github.com/features/mastering-markdown/',
      'Commit requirments': 'https://docs.rs.school/#/en/git-convention',
    },
  },
  {
    week: 1,
    name: 'Markdown & Git',
    description: 'Создать Markdown документ с описанием резюме.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/git-markdown.md',
    type: ['markdown'],
    timeZone: '',
    estimatedTime: '4h',
    dateTime: '1599764400',
    place: 'online',
    comment: 'Рекомендованно использовать реальную информацию о себе',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '1599696000',
    links: {},
  },
  {
    week: 1,
    name: 'CSS Basics',
    description: 'YouTube видео о базовых особенностях CSS',
    descriptionUrl:
      'https://www.youtube.com/watch?v=xdBTX4RMoBE&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=2',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1599922800',
    place: 'online',
    comment: '',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'CSS. Selectors',
    description: '30 CSS-селекторов, которые должны знать начинающие разработчики',
    descriptionUrl: 'http://rightblog.ru/2606',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1599930000',
    place: 'online',
    comment: 'Личный блог о веб-разработке и веб-дизайне',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 1,
    name: 'HTML, CSS & Git Basics',
    description:
      'Создать страницу index.html и стили для нее. Основным содержанием этой страницы является документ Markdown из последней задачи Git и Markdown. Помимо текста нужно добавить свою фотографию или картинку. Страница должна быть развернута на страницах Github и доступна по URL-адресу',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md',
    type: ['HTML task'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1600020000',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1599955200',
    links: {},
  },
  {
    week: 1,
    name: 'CSS positioning and layout (Flex)',
    description: 'Видео лекция Position. Floats. Flex. Semantic. CSS3',
    descriptionUrl:
      'https://www.youtube.com/watch?v=iSQcOjxttNg&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=3',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1599955200',
    place: 'online',
    comment: '',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {},
  },
  {
    week: 2,
    name: 'Git CheatSheet',
    description: 'Вся информация по Гит в одном месте',
    descriptionUrl:
      'https://www.evernote.com/shard/s368/client/snv?noteGuid=b1359883-2b9e-419a-b9de-dd959fc05f05&noteKey=97c0f19486d851b3&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs368%2Fsh%2Fb1359883-2b9e-419a-b9de-dd959fc05f05%2F97c0f19486d851b3&title=Git',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1600041600',
    place: 'online',
    comment: 'Все самое необходимое про Гит в одном месте',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 2,
    name: 'Broswers and IDEs',
    description: 'Видео лекция о браузерах и редакторах кода. Ответы на вопросы',
    descriptionUrl: 'https://www.youtube.com/watch?v=UQavTWiTpnA',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '1.5h',
    dateTime: '1600110000',
    place: 'online',
    comment: 'Лекция будет в виде стрима на YouTube. Продолжителдьность около 1.5 часа',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 2,
    name: 'SASS Basics',
    description: 'Изучение документации по Sass на официальном сайте',
    descriptionUrl: 'https://sass-scss.ru/guide/',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1600171200',
    place: 'online',
    comment: '',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {
      'Preprocessors. Sass': 'https://www.youtube.com/watch?v=JO8DvVZbxDw&feature=youtu.be',
      'SASS. Documentation': 'https://sass-scss.ru/documentation/',
    },
  },
  {
    week: 2,
    name: 'Friday Live Coding',
    description: 'Онлайн создание разметки по макету. Основы БЭМ. Figma. Работа в VS Code',
    descriptionUrl: 'https://www.youtube.com/watch?v=ZAde-IJAHzo&feature=youtu.be',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1600455600',
    place: 'online',
    comment: 'Лекция будет в виде стрима на YouTube. Продолжителдьность около 2 часов',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {
      GitHub: 'https://github.com/ViktoriyaVorozhun/friday-live-coding/tree/develop',
      'Figma layout': 'https://www.figma.com/file/Z7b86A3OdV6kAgoeZBPOZ7/Template-1?node-id=0%3A1',
    },
  },
  {
    week: 2,
    name: 'HTML, CSS & Git Basics Test',
    description: 'Тест по основам HTML, CSS, Git',
    descriptionUrl:
      'https://docs.google.com/forms/d/e/1FAIpQLScHaTjoazbz8mworB6A-mP1tZf_adJLreQ_VwfYQYgOANOC-A/closedform',
    type: ['test'],
    timeZone: '',
    estimatedTime: '18h',
    dateTime: '1600506000',
    place: 'online',
    comment: 'На выполнение теста отводится 12 часов',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '1600473600',
    links: {},
  },
  {
    week: 3,
    name: 'Simple-singolo',
    description:
      'Cверстать страницу согласно макету. Использовать JavaScript для создания адаптивного меню, слайдера, переключения табов в блоке Portfolio.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/simple-singolo.md',
    type: ['HTML task'],
    timeZone: '',
    estimatedTime: '40h',
    dateTime: '1600628400',
    place: 'online',
    comment: 'Необходимо ознакомится с работой Figma',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1600819200',
    links: {
      'Figma layout':
        'https://www.figma.com/file/DhRPIgi3JKRXqAkxaujDLl/Simple-Singolo?node-id=0%3A1',
    },
  },
  {
    week: 4,
    name: 'Simple-singolo',
    description:
      'Выполненное задание по верстке. Использован JavaScript для создания адаптивного меню, слайдера, переключения табов в блоке Portfolio.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/simple-singolo.md',
    type: ['deadline'],
    timeZone: '',
    estimatedTime: '',
    dateTime: '1600819200',
    place: 'online',
    comment: 'Необходимо прикрепить работу на проверку на странице Submit в RS App',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 4,
    name: 'JavaScript. Introduction',
    description: 'Изучение учебника по JavaScript. ',
    descriptionUrl: 'https://learn.javascript.ru/intro',
    type: ['self-study'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1600948800',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 4,
    name: 'Singolo cross-check',
    description: 'Проверка выполнения таска Simple-singolo другими студентами. ',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-2/singolo/singolo-cross-check-1.md',
    type: ['cross-check'],
    timeZone: '',
    estimatedTime: '3h',
    dateTime: '1600948800',
    place: 'online',
    comment: 'На проверку отводится 5 дней',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1601337600',
    links: {},
  },
  {
    week: 4,
    name: 'Friday Live Coding',
    description: 'Продолжение работы с макетом. Подключение припроцессоров.',
    descriptionUrl: 'https://www.youtube.com/watch?v=BJENQIX2e2o&feature=youtu.be',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1601060400',
    place: 'online',
    comment: '',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {},
  },
  {
    week: 5,
    name: 'Codewars. Basics',
    description: 'Задания для практики решения JavaScript тасков на специальной платформе Codewars',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic.md',
    type: ['codewars'],
    timeZone: '',
    estimatedTime: '20h',
    dateTime: '1601251200',
    place: 'online',
    comment: 'После завершения таски ее нужно засабмитить в RS App',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1601769600',
    links: {},
  },
  {
    week: 5,
    name: 'Friday Live Coding',
    description: 'Продолжение работы с макетом.  Стилизация страницы. Подключение normalize.css',
    descriptionUrl: 'https://www.youtube.com/watch?v=fooyYgIuZe8&feature=youtu.be',
    type: ['lecture'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1601492400',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 5,
    name: 'Codewars. Basics',
    description: 'Задания для практики решения JavaScript тасков на специальной платформе Codewars',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic.md',
    type: ['deadline'],
    timeZone: '',
    estimatedTime: '',
    dateTime: '1601769600',
    place: 'online',
    comment: 'После завершения таски ее нужно засабмитить в RS App',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 5,
    name: 'Calculator',
    description:
      'Создание калькулятора, выполняющего математические операции. Отличное объяснение, единственное в этой подборке на русском языке. Код немного устарел: всё ещё используются объявления переменных var вместо const и let, обычные функции, вместо стрелочных. Но логика создания приложения осталась неизменной.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-1-calculator',
    type: ['JS task', 'optional'],
    timeZone: '',
    estimatedTime: '10h',
    dateTime: '1601838000',
    place: 'online',
    comment:
      'Постарайтесь разобраться, почему код пишется так, а не иначе, понять логику автора приложения, не просто повторить готовую работу, но улучшить её, исправить замеченные ошибки и неточности, внести в неё что-то своё.',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {},
  },
  {
    week: 6,
    name: 'JS Basics Video',
    description: 'Для повторения и закрепления изученного материала',
    descriptionUrl: 'https://www.youtube.com/playlist?list=PLY4rE9dstrJymG1GyPLgOKsJNq9r-p6pX',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1601899200',
    place: 'online',
    comment: 'Отличный плейлист от loftblog 24 видео',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 6,
    name: 'JS. DOM',
    description:
      'Подключение первого скрипта\nОбъектная модель документа\nКлюч к пониманию языка\nСвойства, события, методы\ninnerHTML и style\nОбработка событий\nСлайдер фотографий в 20 строк',
    descriptionUrl: 'https://www.youtube.com/watch?v=-2WiaSvOj78&feature=youtu.be',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1602072000',
    place: 'online',
    comment: 'Вебинары Дмитрия Лаврика, направленные на понимание JavaScript и его особенностей',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 6,
    name: 'Webpack',
    description: 'Введение в Webpack, установка, плагины',
    descriptionUrl: 'https://www.youtube.com/watch?v=eSaF8NXeNsA&feature=youtu.be',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '2h',
    dateTime: '1602158400',
    place: 'online',
    comment: 'Курс от Владилена Минина по webpack считается одним из лучших',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {},
  },
  {
    week: 6,
    name: 'Codewars. Basics-1',
    description: 'Задания для практики решения JavaScript тасков на специальной платформе Codewars',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic-1.md',
    type: ['codewars'],
    timeZone: '',
    estimatedTime: '18h',
    dateTime: '1602183600',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1602720000',
    links: {},
  },
  {
    week: 7,
    name: 'Advanced JS',
    description:
      'Изучение prototype, call, bind, this, замыкания, event loop, , асинхронность, промисы, классы и т д',
    descriptionUrl:
      'https://www.youtube.com/watch?v=aQkgUUmUJy4&list=PLqKQF2ojwm3l4oPjsB9chrJmlhZ-zOzWT',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1602504000',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 7,
    name: 'Codewars. Basics-1',
    description: 'Задания для практики решения JavaScript тасков на специальной платформе Codewars',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic-1.md',
    type: ['deadline'],
    timeZone: '',
    estimatedTime: '',
    dateTime: '1602720000',
    place: 'online',
    comment: 'Задание нужно засабмитить в RS App',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 8,
    name: 'Advanced JS Test',
    description: 'Тест по продвинутым функциям JavaScript. Ссылка на тест будет в Дискорде. ',
    descriptionUrl: '',
    type: ['test'],
    timeZone: '',
    estimatedTime: '12h',
    dateTime: '1602936000',
    place: 'online',
    comment: 'На выполнение теста отводится 12 часов',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1602892800',
    links: {},
  },
  {
    week: 9,
    name: 'Rain-drops',
    description:
      'Необходимо создать приложение - тренажёр по математике, позволяющий закрепить навыки арифметических действий: сложения, вычитания, умножения и деления.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/raindrops.md',
    type: ['JS task', 'optional'],
    timeZone: '',
    estimatedTime: '40h',
    dateTime: '1603134000',
    place: 'online',
    comment: '',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '1603584000',
    links: {},
  },
  {
    week: 10,
    name: 'Codewars. Basics-2',
    description: 'Задания для практики решения JavaScript тасков на специальной платформе Codewars',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic-2.md',
    type: ['codewars'],
    timeZone: '',
    estimatedTime: '18h',
    dateTime: '1603652400',
    place: 'online',
    comment: 'Задание нужно засабмитить в RS App',
    organizer: ['2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 10,
    name: 'Rain-drops',
    description:
      'Необходимо создать приложение - тренажёр по математике, позволяющий закрепить навыки арифметических действий: сложения, вычитания, умножения и деления.',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/raindrops.md',
    type: ['deadline'],
    timeZone: '',
    estimatedTime: '',
    dateTime: '1603584000',
    place: 'online',
    comment: '',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 10,
    name: 'fancy-weather',
    description: 'Вам необходимо создать приложение - прогноз погоды',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/fancy-weather.md',
    type: ['JS task'],
    timeZone: '',
    estimatedTime: '60h',
    dateTime: '1603825200',
    place: 'online',
    comment:
      'В предложенный макет можно вносить свои изменения с целью его улучшения, не удаляя и не упрощая представленные на макете элементы дизайна',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '1604016000',
    links: {
      'Figma layout':
        'https://www.figma.com/file/3aQwTNcZWg5CTuvlQ1t5MQ/fancy-weather?node-id=0%3A1',
      Demo: 'https://deadline2020-fancy-weather.netlify.app/',
    },
  },
  {
    week: 12,
    name: 'RS conference',
    description:
      'Конференция Front-end разработчиков. На мероприятии выступят специалистыFront-end разработки из EPAM. Будут представлен live coding макета, выступления по JavaScript темам и многое другое',
    descriptionUrl: 'https://rsconf.by/',
    type: ['conference'],
    timeZone: '',
    estimatedTime: '20h',
    dateTime: '1604923200',
    place: 'Minsk, ',
    comment: 'Для участия в конференции нужно зарегистрироваться ',
    organizer: ['2hrQVm7BAzWdmMQpzJAw', 'DVgluQnLGTg9ggTi6A4N'],
    deadline: '',
    links: {},
  },
  {
    week: 12,
    name: 'Front-end evening',
    description:
      'Встреча посвященная Front-end разработки. Обсуждения основных сложностей на пути Front-end разработчика, road map. Выступление с мотивирующими историями от выпускников школы RS School',
    descriptionUrl: 'https://community-z.com/events/rss2019q3-meetup-2',
    type: ['meet-up'],
    timeZone: '',
    estimatedTime: '5h',
    dateTime: '1605466800',
    place: 'Minsk',
    comment: 'Для участия нужно зарегистрироваться ',
    organizer: ['zom0bgoUBztJLlMhDEvh', '2hrQVm7BAzWdmMQpzJAw'],
    deadline: '',
    links: {},
  },
  {
    week: 13,
    name: 'Interview questions',
    description: 'Список вопросов для подготовки к финальному собеседованию. ',
    descriptionUrl:
      'https://github.com/lydiahallie/javascript-questions/blob/master/ru-RU/README.md',
    type: ['materials'],
    timeZone: '',
    estimatedTime: '0.5h',
    dateTime: '1606824000',
    place: 'online',
    comment: '',
    organizer: ['zom0bgoUBztJLlMhDEvh'],
    deadline: '',
    links: {},
  },
  {
    week: 13,
    name: 'Interview',
    description: 'Финальное собеседование по завершению курса. Основы JavaScript, HTML, CSS',
    descriptionUrl:
      'https://github.com/lydiahallie/javascript-questions/blob/master/ru-RU/README.md',
    type: ['interview'],
    timeZone: '',
    estimatedTime: '1.5h',
    dateTime: '1606935600',
    place: 'online',
    comment: 'Собеседование нужно пройти в течении 2 недель',
    organizer: ['DVgluQnLGTg9ggTi6A4N'],
    deadline: '1608681600',
    links: {
      'Interview Questions':
        'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/interview-corejs.md',
    },
  },
];

export default DATA;
