// description
export default [
  {
    id: '1',
    week: '0',
    dateTime: '1599087906000',
    deadline: '1599188006000',
    type: ['js task'],
    place: 'Minsk',
    event: {
      name: 'Songbird',
      url: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/songbird.md',
    },
    description: 'Здесь вы научитесь терпеть боль',
    links: [
      { name: 'LearnJs', url: 'https://learnjs.ru' },
      { name: 'GitHub', url: 'https://github.com' },
    ],
    organizer: [{ name: 'Юлия', url: 'https://github.com/yuliahope' }],
    comment: 'Вопросы можно задать в дискорде',
  },
  {
    id: '2',
    week: '0',
    dateTime: '1599207720000',
    deadline: '1599388006000',
    type: ['additional', 'js task'],
    place: 'Minsk',
    event: {
      name: 'Codewars React',
      url:
        'https://github.com/rolling-scopes-school/tasks/blob/f504966947a9f3e85a27f6401e7a6870f870f392/tasks/codewars-react.md',
    },
    description: 'Задачки на знание реакт-компонентов',
    links: [{ name: 'React', url: 'https://reactjs.org/' }],
    organizer: [{ name: 'Юлия', url: 'https://github.com/yuliahope' }],
    comment: 'Задание не обязательное',
  },
  {
    id: '3',
    week: '1',
    dateTime: '1599253464064',
    deadline: '',
    type: ['lecture'],
    place: 'Online',
    event: { name: 'Как работать с браузером', url: 'https://www.youtube.com/' },
    description: 'Лекция про браузеры)',
    links: [{ name: 'Browsers and IDEs', url: 'https://www.youtube.com/watch?v=nd2VYxOsOwY' }],
    organizer: [
      { name: 'Юлия', url: 'https://github.com/yuliahope' },
      { name: 'Клон Юлии', url: 'https://github.com/yuliahope' },
    ],
    comment: 'Обязательно посмотреть!',
  },
];

// [
//   {
//     id: '1',
//     dateTime: '1599087906000',
//     place: 'Minsk',
//     name: 'Songbird',
//     broadcastUrl: '',
//     type: ['js task'],
//     organizer: 'https://github.com/yuliahope',
//     descriptionUrl: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/songbird.md',
//     detailsUrl: '',
//     comment: '',
//   },
//   {
//     id: '2',
//     dateTime: '1599207720000',
//     place: 'Minsk',
//     name: 'Codewars React',
//     broadcastUrl: '',
//     type: ['deadline', 'additional'],
//     organizer: 'https://github.com/yuliahope',
//     descriptionUrl:
//       'https://github.com/rolling-scopes-school/tasks/blob/f504966947a9f3e85a27f6401e7a6870f870f392/tasks/codewars-react.md',
//     detailsUrl: '',
//     comment: '',
//   },
//   {
//     id: '3',
//     dateTime: '1599253464064',
//     place: 'Minsk',
//     name: 'Schedule',
//     broadcastUrl: '',
//     type: ['js task'],
//     organizer: 'https://github.com/yuliahope',
//     descriptionUrl: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/schedule.md',
//     detailsUrl: '',
//     comment: '',
//   },
// ];
