export default [
  {
    id: '1',
    dateTime: '1599087906000',
    place: 'Minsk',
    name: 'Songbird',
    broadcastUrl: '',
    type: ['js task'],
    organizer: 'https://github.com/yuliahope',
    descriptionUrl: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/songbird.md',
    detailsUrl: '',
    comment: '',
  },
  {
    id: '2',
    dateTime: '1599207720000',
    place: 'Minsk',
    name: 'Codewars React',
    broadcastUrl: '',
    type: ['deadline'],
    organizer: 'https://github.com/yuliahope',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/f504966947a9f3e85a27f6401e7a6870f870f392/tasks/codewars-react.md',
    detailsUrl: '',
    comment: '',
  },
  {
    id: '3',
    dateTime: '1599253464064',
    place: 'Minsk',
    name: 'Schedule',
    broadcastUrl: '',
    type: ['js task'],
    organizer: 'https://github.com/yuliahope',
    descriptionUrl: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/schedule.md',
    detailsUrl: '',
    comment: '',
  },
];
