export default [
  {
    id: '1',
    week: '0',
    dateTime: '1599087906000',
    deadline: '1599188006000',
    type: ['js task'],
    place: 'Online',
    estimatedTime: '8h',
    timeZone: '',
    name: 'Songbird',
    descriptionUrl: 'https://github.com/rolling-scopes-school/tasks/blob/master/tasks/songbird.md',
    description: 'Здесь вы научитесь терпеть боль',
    links: [
      { name: 'LearnJs', url: 'https://learnjs.ru' },
      { name: 'GitHub', url: 'https://github.com' },
    ],
    organizer: ['id1'],
    comment: 'Вопросы можно задать в дискорде',
  },
  {
    id: '2',
    week: '0',
    dateTime: '1599207720000',
    deadline: '1599388006000',
    type: ['additional', 'js task'],
    place: 'Minsk',
    estimatedTime: '8h',
    timeZone: '',
    name: 'Codewars React',
    descriptionUrl:
      'https://github.com/rolling-scopes-school/tasks/blob/f504966947a9f3e85a27f6401e7a6870f870f392/tasks/codewars-react.md',
    description: 'Задачки на знание реакт-компонентов',
    links: [{ name: 'React', url: 'https://reactjs.org/' }],
    organizer: ['id3'],
    comment: 'Задание не обязательное',
  },
  {
    id: '3',
    week: '1',
    dateTime: '1599253464064',
    deadline: '',
    type: ['lecture'],
    place: 'Online',
    estimatedTime: '8h',
    timeZone: '',
    name: 'Как работать с браузером',
    descriptionUrl: 'https://www.youtube.com/',
    description: 'Лекция про браузеры)',
    links: [{ name: 'Browsers and IDEs', url: 'https://www.youtube.com/watch?v=nd2VYxOsOwY' }],
    organizer: ['id1', 'id2'],
    comment: 'Обязательно посмотреть!',
  },
  // {
  //   id: '4',
  //   week: '1',
  //   dateTime: '1599469200000',
  //   deadline: '',
  //   type: ['self-study'],
  //   place: 'Online',
  //   event: { name: 'HTML online course', url: 'https://ru.code-basics.com/languages/html' },
  //   description: 'Базовый курс, который даст понимание основ HTML',
  //   links: [{ name: 'Code basics', url: 'https://ru.code-basics.com/' }],
  //   organizer: [{ name: 'RSSchool', url: 'https://docs.rs.school/#' }],
  //   comment:
  //     'На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)/ Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения заданий нужно посмотреть и послушать как студент решает пройденные им таски',
  // },
  // {
  //   id: '5',
  //   week: '1',
  //   dateTime: '1599555600000',
  //   deadline: '',
  //   type: ['lecture'],
  //   place: 'Online',
  //   event: { name: 'Как работать с браузером', url: 'https://www.youtube.com/' },
  //   description: 'Лекция про браузеры)',
  //   links: [{ name: 'Browsers and IDEs', url: 'https://www.youtube.com/watch?v=nd2VYxOsOwY' }],
  //   organizer: [
  //     { name: 'Юлия', url: 'https://github.com/yuliahope' },
  //     { name: 'Клон Юлии', url: 'https://github.com/yuliahope' },
  //   ],
  //   comment: 'Обязательно посмотреть!',
  // },
  // {
  //   id: '6',
  //   week: '1',
  //   dateTime: '1599555600000',
  //   deadline: '',
  //   type: ['lecture'],
  //   place: 'Online',
  //   event: { name: 'Как работать с браузером', url: 'https://www.youtube.com/' },
  //   description: 'Лекция про браузеры)',
  //   links: [{ name: 'Browsers and IDEs', url: 'https://www.youtube.com/watch?v=nd2VYxOsOwY' }],
  //   organizer: [
  //     { name: 'Юлия', url: 'https://github.com/yuliahope' },
  //     { name: 'Клон Юлии', url: 'https://github.com/yuliahope' },
  //   ],
  //   comment: 'Обязательно посмотреть!',
  // },
];
